#5.1 순서가 없는 범주형 특성 인코딩하기

*사이킷런의 LabelBinarizer 사용*

In [ ]:

#라이브러리 임포트
import numpy as np
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
#특성 만듬
feature = np.array([["Texas"],
                    ["California"],
                    ["Texas"],
                    ["Delaware"],
                    ["Texas"]])

# 원-핫 인코더 만듬
one_hot = LabelBinarizer()

# 특성을 원-핫 인코딩
one_hot.fit_transform(feature)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
one_hot.fit(feature)

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [ ]:
one_hot.transform(feature)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# 특성의 클래스를 확인
one_hot.classes_

array(['California', 'Delaware', 'Texas'], dtype='<U10')

In [ ]:
# 원-핫 인코딩 되돌리기
one_hot.inverse_transform(one_hot.transform(feature))

array(['Texas', 'California', 'Texas', 'Delaware', 'Texas'], dtype='<U10')

*다중 클래스를 인코딩하기*

In [ ]:
# 다중 클래스 특성 만듬
multiclass_feature = [("Texas", "Florida"),
                      ("California", "Alabama"),
                      ("Texas", "Florida"),
                      ("Delware","Florida"),
                      ("Texas","Albama")]

# 다중 클래스 원-핫 인코더 만듬
one_hot_multiclass=MultiLabelBinarizer()

# 다중 클래스 특성을 원-핫 인코딩
one_hot_multiclass.fit_transform(multiclass_feature)

array([[0, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 1]])

In [ ]:
# 클래스 확인
one_hot_multiclass.classes_

array(['Alabama', 'Albama', 'California', 'Delware', 'Florida', 'Texas'],
      dtype=object)

*OneHotEncoder 클래스 사용 - 희소 배열 반환*

In [ ]:
# 여러 개의 열이 잇는 특성 배열 만듬
feature=np.array([["Texas",1],
                  ["California",1],
                  ["Texas",3],
                  ["Delaware",1],
                  ["Texas",1]])

one_hot_encoder=OneHotEncoder(sparse=False)
one_hot_encoder.fit_transform(feature)

array([[0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0.]])

In [ ]:
# 클래스 확인
one_hot_encoder.categories_

[array(['California', 'Delaware', 'Texas'], dtype='<U10'),
 array(['1', '3'], dtype='<U10')]

*판다스를 사용해서 원-핫 인코딩*

In [ ]:
# 라이브러리 임포트

import pandas as pd

In [ ]:
# 특성으로 더미(dummy) 변수 생성
pd.get_dummies(feature[:,0])

California  Delaware  Texas
0           0         0      1
1           1         0      0
2           0         0      1
3           0         1      0
4           0         0      1

#5.2 순서가 있는 범주형 특성 인코딩하기

In [ ]:
replace 메서드를 사용하여 문자열 레이블을 수치값으로 반환

In [ ]:
#특성 만들기
dataframe=pd.DataFrame({"Score":["Low","Low","Medium","Medium","High"]})

#매핑 딕셔너리 만들기
scale_mapper={"Low":1,
              "Medium":2,
              "High":3}

#특성을 정수로 변환
dataframe["Score"].replace(scale_mapper)

0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64

In [ ]:
# 클래스에 매핑하는 수치값에 주의를 기울여야 한다.

dataframe=pd.DataFrame({"Score":["Low","Low","Medium","Medium","High","Barely More Than Medium"]})
scale_mapper={"Low":1,
              "Medium":2,
              "Barely More Than Medium":2.1,
              "High":3}
dataframe["Score"].replace(scale_mapper)

0    1.0
1    1.0
2    2.0
3    2.0
4    3.0
5    2.1
Name: Score, dtype: float64

*OrdinalEncoder을 사용해 클래스 범주를 순서대로 변환*

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

features=np.array([["Low",10],
                   ["High",50],
                   ["Medium",3]])

ordinal_encoder=OrdinalEncoder()
ordinal_encoder.fit_transform(features)


array([[1., 0.],
       [0., 2.],
       [2., 1.]])

In [ ]:
ordinal_encoder.categories_

#5.3 특성 딕셔너리를 인코딩하기

*DictVectorizer 을 사용*

In [ ]:
# 라이브러리를 임포트

from sklearn.feature_extraction import DictVectorizer

# 딕셔너리를 만듭니다.
data_dict = [{"Red":2, "Blue":4},
             {"Red":4, "Blue":3},
             {"Red":1, "Yellow":2},
             {"Red":2, "Yellow":2}]

# Dicvectorizer 객체를 만듭니다
dicvectorizer = DictVectorizer(sparse=False)

# 딕셔너리를 특성 행렬로 변환합니다
features = dicvectorizer.fit_transform(data_dict)

features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [ ]:
# 특성 이름을 얻기
features_names=dicvectorizer.get_feature_names()

# 특성 이름 확인
features_names

['Blue', 'Red', 'Yellow']

In [ ]:
# 판다스 DaTaFrame으로 출력한다

import pandas as pd

pd.DataFrame(features, columns=features_names)

Blue  Red  Yellow
0   4.0  2.0     0.0
1   3.0  4.0     0.0
2   0.0  1.0     2.0
3   0.0  2.0     2.0

#5.4 누락된 클래스 값 대체하기

머신러닝 분류 알고리즘을 훈련하여 누락된 값 예측

KNN 분류기를 사용


In [ ]:
# 라이브러리를 임포트
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

# 범주형 특성을 가진 특성 행렬을 만듬
X = np.array([[0, 2.10, 1.45],
              [1, 1.18, 1.33],
              [0, 1.22, 1.27],
              [1,-0.21,-1.19]])

# 범주형 특성에 누락된 값이 있는 특성 행렬을 만듬
X_with_nan = np. array([[np.nan, 0.87, 1.31],
                        [np.nan, -0.67, -0.22]])


In [ ]:
# KNN 학습기를 훈련
clf=KNeighborsClassifier(3,weights='distance')
trained_model = clf.fit(X[:,1:], X[:,0])

# 누락된 값의 클래스를 예측
imputed_values = trained_model.predict(X_with_nan[:,1:])

# 예측된 클래스와 원본 특성을 열로 합침
X_with_imputed = np.hstack((imputed_values.reshape(-1,1), X_with_nan[:,1:]))

# 두 특성 행렬을 연결
np.vstack((X_with_imputed, X))

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

누락된 값을 특성에서 가장 자주 등장하는 값으로 채우기

In [ ]:
from sklearn.impute import SimpleImputer

# 두 개의 특성 행렬을 합침
X_complete = np.vstack((X_with_nan, X))

imputer = SimpleImputer(strategy='most_frequent')
imputer.fit_transform(X_complete)

array([[ 0.  ,  0.87,  1.31],
       [ 0.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

#5.5. 불균형한 클래스 다루기

In [ ]:
# 라이브러리를 임포트

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

# 붓꽃 데이터 적재
iris = load_iris()

# 특성 행렬 만들기
features = iris.data

# 타깃 벡터 만들기
target = iris.target

# 처음 40개 샘플 삭제
features = features[40:,:]
target = target[40:]

# 클래스 0을 음성 클래스로 하는 이진 타깃 벡터를 만듭니다
target = np.where ((target==0),0,1)

target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

*클래스 가중치 매개변수를 사용해 알고리즘이 불균형한 클래스 조정*

In [ ]:
# 가중치 만듬
weights = {0: .9, 1:0.1}

# 가중치를 부여한 랜덤 포레스트 분류기 만듬
RandomForestClassifier(class_weight=weights)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                       class_weight={0: 0.9, 1: 0.1}, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [ ]:
# 균형잡힌 클래스 가중치로 랜덤 포레스트 모델 훈련
RandomForestClassifier(class_weight="balanced")

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

* 업샘플링 : 소수 클래스의 샘플을 늘린다
* 다운샘플링 : 다수 클래스의 샘플을 줄인다

다운샘플링

In [ ]:
# 각 클래스의 샘플 인덱스 추출
i_class0=np.where(target==0)[0]
i_class1=np.where(target==1)[0]

# 각 클래스의 샘플 개수
n_class0 = len(i_class0)
n_class1 = len(i_class1)

# 클래스 0의 샘플만큼 클래스 1에서 중복을 허용하지 않고 랜덤하게 샘플 뽑기
i_class1_downsampled = np.random.choice(i_class1, size=n_class0, replace=False)

# 클래스 0의 타깃 벡터와 다운샘플링된 클래스 1의 타깃 벡터를 합침
np.hstack((target[i_class0], target[i_class1_downsampled]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# 클래스 0의 특성 행렬과 다운샘플링된 클래스 1의 특성 행렬을 합칩니다.
np.vstack((features[i_class0,:], features[i_class1_downsampled, :]))[0:5]


array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4]])

업샘플링

In [ ]:
# 클래스 1의 샘플 개수만큼 클래스 0에서 중복을 허용하여 랜덤하게 샘플 선택
i_class0_upsampled = np.random.choice(i_class0, size=n_class1, replace=True)

# 클래스 0의 업샘플링된 타깃 벡터와 클래스 1의 타깃 벡터를 합침
np.concatenate((target[i_class0_upsampled], target[i_class1]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [ ]:
# 클래스 0의 업샘플링된 특성 행렬과 클래스 1의 특성 행렬을 합침
np.vstack((features[i_class0_upsampled,:], features[i_class1,:]))[0:5]

array([[5.1, 3.8, 1.6, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.4, 3.2, 1.3, 0.2]])